### ISSUE TITLE
 Question about using .env.keys in development

### ISSUE THREAD

**Issue by jaesbit** [dotenvx/dotenvx#122]
Hello, I am using this library, and I find it very useful, but I think it cannot be used directly with just a `.env.vault` and `.env.keys` file and automatically decode it, and the `DOTENV_KEY` variable must be passed. 
If this is true, do you have plans to make it possible to use it without defining the `DOTENV_KEY` variable and use it directly from `.env.keys`?

It would be a great "must-have" for the development environment and improve usability when developing.

**Comment by motdotla** [comment]
> using this library, and I find it very useful

glad you are enjoying it. it's still early and only going to get better and better.






> automatically decode it, and the DOTENV_KEY variable must be passed

yes, currently the DOTENV_KEY variable must be passed like so:

```
DOTENVX_KEY=<key here> dotenvx run -- node index.js
# decrypted injection
```

this is because we currently recommend using your `.env` file in development via `dotenvx run -- yourcommand` and using the `.env.vault` file in production.

that said, if you only have your .env.vault and .env.keys file, you can currently run `dotenvx decrypt` and it will auto decrypt your `.env.vault` to `.env*` files instantly.

> would be a great "must-have" for the development environment and improve usability when developing

could you elaborate on this some more? don't you already have your `.env` file next to your `.env.vault` in your development environment? or is this when a teammate is pulling the .env.keys and .env.vault files for the first time and do not yet have their `.env` file?

**Comment by jaesbit** [comment]
Sure, my case and question is about how to share with team members or repo-accessible members. Obviously, we won't upload a `DOTENV_KEY` or `.env.keys` to the repo, as it would defeat the purpose. However, it would be nice to be able to pass the `.keys` file to the teammate so they can execute it. During development, it would be great if we didn't have to run export `DOTENV_KEY=...` or add `DOTENV_KEY=... dotenvx run - ...` before the command line. Then, when we deploy to a production environment, we can set the `DOTENV_KEY` environment variable and it will work perfectly.


With that said, I'm not sure how you would view not depending (at least in Node.js) on running `dotenvx run --`, as from what I've seen in the library, it should be able to decode by reading the environment variables (for production) or using the `.keys` file in development.

**Comment by motdotla** [comment]
> how to share with team members or repo-accessible members

this is in beta. it's called 'hub'. try it out by pushing your `.env.keys`with `dotenvx hub push`.

team features are not really there yet but they are being actively worked on.

> During development, it would be great if we didn't have to run ...

yes, once we get the `dotenvx hub pull` command this will be possible. and then we'll probably just tie it into the `run` command so that it is smart and always injects the latest values if working with a team.
