### ISSUE TITLE
Difficulty Including Root-Level .env.vault File in subdirectory Dockerfile Builds

### ISSUE THREAD

**Issue by spookyuser** [dotenvx/dotenvx#159]
In a monorepo setup, I prefer having a single set of production and development .env files at the root level that can be shared by all the projects within the monorepo. However, I'm facing a challenge in elegantly including the root-level .env file (e.g., .env.vault) in the Dockerfile builds for a project in a repo, for example my backend project in a structure that looks like this:

```sh
/ root
  |- .env.vault
  |- Backend
     |- Dockerfile
```
     
I've tried using an additional build context argument in the docker build command for the backend, like `--build-context envs=../../`, along with a .dockerignore file at the root level that ignores everything except the .env.vault file. While this approach works, it doesn't seem to be compatible with docker builds i can't control precisely, specifically Railway's build command doesn't seem to work with the build context.

I was wondering if adding a `dotenvx pull` but with a preconfigured token provided in the cli would be one way? then i could include `RUN dotenvx pull --token=...` to get a fresh copy of the .env.vault in any dockerfile.

Thanks sm!

**Comment by motdotla** [comment]
yeah, this is a docker thing because of constraints on its build context. I would say create a symlink, but Docker also doesn't support following symlinks outside of its build context.

we are considering some kind of just-in-time API call pull command like you describe, but that will likely be a paid feature because it requires maintaining a hosted service that is always up.

the most elegant solution for you at this time, might be just to copy the .env.vault under Backend just before building the Docker image via a little build script. something like this:

```
#!/bin/bash
cp ../.env.vault .env.vault
docker build -t your-image-name:your-tag .
rm .env.vault
```
