### ISSUE TITLE
[Security] Alternative docker path than "https://dotenvx.sh/" which exposes risk for supply chain attack

### ISSUE THREAD

**Issue by douglasg14b** [dotenvx/dotenvx#204]
The [docker guide ](https://dotenvx.com/docs/platforms/docker#run-dotenvx)indicates that this should be installed from `https://dotenvx.sh/`. This is a **_very high_** risk for supply chain attack, and is actually entirely disallowed in some orgs due to this known risk.

How else can we use this within docker without exposing this risk?

**Comment by motdotla** [comment]
can you elaborate why this is a **very high** risk - are you referring to if we would lose control over our own domain `dotenvx.sh`?

there are install instructions here if you prefer to install from github releases: https://dotenvx.com/docs/install#git-hub-releases

**Comment by douglasg14b** [comment]
> are you referring to if we would lose control over our own domain 

Yep, that's exactly it. Either you lose control, or poor security posture causes control to be lost either knowingly or unknowingly. Making installs from your site a malware delivery method. 

These are common attacks on developer tools, 3rd party sites for popular tools being popular targets since they usually don't have automated monitoring & alerting , or are intentionally designed to avoid delivering malware with external checksum validation.

The docs should probably highlight this risk, and even avoid it by pointing the install script to the github repo instead.

**Comment by douglasg14b** [comment]
To be clear, I'm not attacking you or anything. I'm just concerned.

This is something running in automated pipelines inside internal networks, and inside docker containers that have will have access, in many cases, to organizational secrets, user data....etc

_Automatically_ executing a script retrieved from a 3rd party website with an unknown security posture is a lot of risk. And is a juicy target for data exfiltration.

**Comment by motdotla** [comment]
security is a spectrum - even trusted CDNs have supply chain risk. 

regarding the domain it is very hard to lose one with our current setup:

1. unique password for our domain registrar
2. mult-factor auth setup
3. multiple credit cards on file in case one fails purchase
4. auto-renewal turned on
5. trusted registrar that is 16 years old, profitable, and not VC-funded
6. whois privacy
7. dedicated domain ONLY for serving up the binary and installer. no other code runs on that domain/server.

that said, we did think about what you are discussing but my conclusion is the opposite of yours. the control of serving over your own domain has MORE strength than serving over a 3rd party CDN.

if we served over a 3rd party CDN, an attacker would only need to gain access to our credentials of that CDN to execute a supply chain attack - there are many many historical examples of this happening in the real world.

if we serve over our own domain, they need to somehow determine where our service is hosted, and then gain access to the server - which requires a combination of an ssh key, password, and a multi-factor step. there are comparatively few historical examples of this happening in the real world.

we also publish the code for dotenvx.sh publicly - for audit reasons, and for others to try and find potential security risks - at [https://github.com/dotenvx/dotenvx.sh](https://github.com/dotenvx/dotenvx.sh). it's readable and infinitely less complex than the code running CDNs. (there is a good argument to be made that CDNs are MORE exploitable because their code is private, always/often changing, and they have many more features/complexity. complexity = security risk.)

in general, i disagree with the assumed premise that centralized is safer.

all that said, executing an `installer.sh` script is not for everyone and I applaud those who instead install themselves, but as long as we are discussing along those lines we should be discussing installing and building directly from source code you've personally audited yourself. in other words, there is a spectrum here that is useful to different teams. we've tried to serve that spectrum well. an enterprise is going to put older proven stable versions of dotenvx behind their own artifactory (or the like). hobbyists and small teams are going to run curl/brew/npm. and someone extra security minded like yourself is going to download from our releases and unpack the lib yourself. also, keep in mind our current target are hobbyists/small teams. they are willing to experiment with new improvements to software far ahead of enterprises.

i do need to get the checksum file added back into our publishing process. will do so soon.

also, i did feel your post was too alarmist. please keep in mind, i've personally maintained a library with huge supply chain attack risk for the past ten years - https://www.npmjs.com/package/dotenv. ultimately, a lot of this boils down to trust, which is earned only after time and action - something i intend to earn from the community as i did with dotenv.
