### ISSUE TITLE
Encryption - effective?

### ISSUE THREAD

**Issue by stereokai** [dotenvx/dotenvx#253]
Dotenv is amazing and this new version looks just as great - but I'm personally struggling to comprehend to which extend does key encryption enhance security in a CI/CD environment. Would you be so kind to help me understand this extra layer?

1. In practice, how are `.env.keys` and `DOTENV_PRIVATE_KEY` provided to the CI/CD runner, or where does it get them from?
2. Since eventually the CI/CD runner will need to have both `.env.keys` as well as `DOTENV_PRIVATE_KEY`, to decrypt and access the keys, am I correct to understand that encrypting the keys is "only" an additional defence against saving unencrypted keys on the CI/CD provider and it getting hacked, and nothing more? Or am I missing something?

Thanks for clarifying.

**Comment by motdotla** [comment]
you're welcome. thanks for using them!

I'll use the example of GitHub Actions CI for my answers:

> 1. In practice, how are .env.keys and DOTENV_PRIVATE_KEY provided to the CI/CD runner, or where does it get them from?

The `DOTENV_PRIVATE_KEY_CI` is set on github actions secrets [#1](https://dotenvx.com/docs/cis/github-actions#set-decryption-key)

> 2. Since eventually the CI/CD runner will need to have both .env.keys as well as DOTENV_PRIVATE_KEY, to decrypt and access the keys..

It only needs the `DOTENV_PRIVATE_KEY*`. The `.env.keys` file is just a convenient place to coalesce all your private keys (development, ci, production) in one place.

> additional defence against saving unencrypted keys on the CI/CD provider and it getting hacked

Yes, but let's step through a real world scenario - [the circleci data breach](https://www.google.com/search?client=safari&rls=en&q=circleci+data+breach&ie=UTF-8&oe=UTF-8).

In this data breach the attacker:

1. Gained access to environment variables
2. Did NOT gain access to code

For anyone putting environment variables like their STRIPE_API_KEY in CircleCi, their business was immediately put at risk. They had to rotate EVERY key they had stored on CircleCi.

But for those using a `DOTENV_PRIVATE_KEY*` they were not put at risk because the attacker did not have the encrypted `.env` files (in code) to decrypt.

In addition to that there are workflow benefits. If you need to run things in a second ci service or move to a new service, you can just reset your `DOTENV_PRIVATE_KEY*`. You don't have to migrate over ALL your keys again. Less chance of fat-fingering something this way.

Does this make sense? Thoughts?

**Comment by stereokai** [comment]
Thank you so much for the clarification. However I still have a missing
piece - how are the encrypted keys made available to the CI so that dotenvx
can decrypt them using `DOTENV_PRIVATE_KEY` if not by providing `.env.keys`
to the CI somehow?

Also concerning the CircleCI incident, yes, the attacker only gained
environment variables, but those can still be valuable in some cases - for
example, license keys for commercial client-side libraries

**Comment by motdotla** [comment]
> However I still have a missing
piece - how are the encrypted keys made available to the CI so that dotenvx
can decrypt them using `DOTENV_PRIVATE_KEY` if not by providing `.env.keys`

Ah, I think i'm not being clear.

1. You commit your encrypted `.env.ci` file to code - this contains your secrets/config in an encrypted manner
2. You go on your CI and set a single environment variable - `DOTENV_PRIVATE_KEY_CI`
3. When your build runs it uses dotenvx to decrypt your `.env.ci` (using the DOTENV_PRIVATE_KEY_CI) and inject your secrets/config just in time

> Also concerning the CircleCI incident, yes, the attacker only gained
environment variables, but those can still be valuable in some cases - for
example, license keys for commercial client-side libraries

I'm saying just the opposite. The attacker gaining access to those is bad. That's how everyone does things today - which we aer trying to change with dotenvx's pattern. If you use dotenvx, the attacker only gains access to the `DOTENV_PRIVATE_KEY` which is useless on its own.

p.s. keep in mind the `DOTENV_PRIVATE_KEY` and `DOTENV_PUBLIC_KEY` are different. the private one is used for decryption and the public one for encryption.

**Comment by stereokai** [comment]
Thanks 🙏

Yes I understand the concept of encryption with public and private keys.

So basically, you confirmed my point. How likely is it that an attacker
could gain access to both code & private key? Well, how likely is it that
an attacker could get either? What would your answer have been before the
CircleCI breach? And today?

Maybe an alternative would be to keep either the encrypted env variables or
the private key on a secret manager service which using OAuth can authorize
the CI to retrieve either, so that one half of the "pie" is always hosted
separately? Does such a thing even exist?

**Comment by motdotla** [comment]
ok, cool, we're on the same page.

> How likely is it that an attacker could gain access to both code & private key? Well, how likely is it that an attacker could get either? What would your answer have been before the CircleCI breach? And today?

It's a good question. I don't have a good answer, but I think it's safe to say it would be twice as unlikely. So it's arguably a significant improvement.

> Maybe an alternative would be to keep either the encrypted env variables or the private key on a secret manager service

Smart. This would indeed be another level of obfuscation. Then the attacker would have to take 3 steps to get the decrypted values, rather than just two. We plan to support this as part of dotenvx in the future as a paid feature - as a service and/or as tooling to support your own chosen service like AWS Secret Manager, etc.

**Comment by stereokai** [comment]
> I think it's safe to say it would be twice as unlikely. So it's arguably a significant improvement.

Not trying to be contentious here but not necessarily - it obviously depends on how the system is implemented and even on how it's run. In an ideal world - sure. But in an ideal world we wouldn't need to keep secrets 😛 

> Smart. This would indeed be another level of obfuscation. Then the attacker would have to take 3 steps to get the decrypted values, rather than just two. We plan to support this as part of dotenvx in the future as a paid feature - as a service and/or as tooling to support your own chosen service like AWS Secret Manager, etc.

Thanks. It's great to hear support for this is planned. Since many CIs and secret managers already support this approach, how do you see dotenvx implementing it?

**Comment by motdotla** [comment]
i think that is better shown than told. overtime keep your eyes on dotenvx and you'll see.

i'm going to go ahead and close this. thanks for your thoughts.
