### ISSUE TITLE
Question: Any best practices recommended for sharing the encryption keys?

### ISSUE THREAD

**Issue by egonbraun** [dotenvx/dotenvx#267]
First and foremost, I am really glad with this new update and want to start using it right away.

I like the encryption feature but it comes with a couple of trade-offs:

(1) How to share the private and public keys with others?
(2) How to manage dozens or even hundreds of encryption keys that will be created since every project I manage will have a different one?

I would like to hear how you guys are doing it.

I myself am thinking of wrapping `dotenvx` around a command that can talk to an external secrets manager and get the secrets based on the project name defined in the `package.json`. This can also have a shell hook to load/unload those variables everytime I cd into a project directory (kind of like `direnv` does).

The overwall workflow would then be:

1. `cd` into a project
2. Shell hook is triggered
3. It checks if it is a project with a .env
4. Checks for a `package.json` and gets the project name (otherwise use the parent directory name as the project name)
5. Checks local secret manager (e.g. KeyChain in macOS) for the private key
6. Sets the correct environment variables with the value of the private and public keys

Anyway, open to hear more ideas. Thanks!

**Comment by motdotla** [comment]
> I myself am thinking of wrapping dotenvx around a command that can talk to an external secrets manager

great! if you create it, please share it. i hope and imagine `dotenvx` provides a foundation for devs to build all kinds of extension libraries/features on top of it.

and no best practices yet, but I am starting to think hard on that. currently we're managing ours in 1Password - largely manually. we have some ideas on how to improve/automate this tooling.

we'll also likely build our own secret manager. i think the ones on the market are unnecessarily complex.

**Comment by chapati23** [comment]
We’ve solved this problem a few years back by wrapping [sops](https://github.com/getsops/sops)  into package we called strong config https://github.com/strong-config/node

it’s not a shill as it’s very actively maintained anymore but the nice about sops was that it allowed you to use your trusted cloud providers secret management

Meaning your encryption keys could be managed via ie Google Cloud’s Secrets Manager, or AWS etc 

I love the evolution of dotenv, but key management remains an Achilles heel because people will still accidentally commit their keys to git which can only be avoided if the keys are never kept inside the same folder in the first place

so whoever wants to build cloud-based private key management on top of dotenvx => I’ll owe you a beer :)

**Comment by motdotla** [comment]
> accidentally commit their keys to git

there is `dotenvx extgitignore`, `dotenvx ext precommit`, and `dotenvx ext prebuild` to help prevent this

> which can only be avoided if the keys are never kept inside the same folder

i agree that moving the location greatly helps to avoid this issue. we're keeping that in mind for `dotenvx pro`

your strong config looks handy. do you still use it? it's  a wrapper around sops functionality, am i right? or did you create your own permission system on top of it - for role based key access?

my qualms with sops (besides i think it it has a clunky developer experience) is it relies on centralized key management solutions. currently i'm leaning more towards a zero-knowledge setup like 1Password's for dotenvx pro.

the problem with centralized systems is they cause massive damage if they have a security breach. they are a rich ($$$) target. where a zero-knowledge solution moves the risk to the user's machine - a much poorer ($) target.

**Comment by vinnymac** [comment]
This won't work for everyone, but if you happen to be using AWS or Vercel, [aws ssm](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ssm/get-parameter.html) and [vercel env](https://vercel.com/docs/cli/env) have both worked for me to share the private keys with teammates across various projects.

**Comment by chapati23** [comment]
> your strong config looks handy. do you still use it? it's a wrapper around sops functionality, am i right? or did you create your own permission system on top of it - for role based key access?

Yeah it started mainly as a wrapper around sops and then we extended it with some other features such as strongly typed configs to defend against config drift (meaning someone adding some config to .env.prod but forgetting to also add it to ie .env.staging and .env.local etc)

I’d agree that sops’ UX didn’t feel great (which is probably why we wrapped it 😅).

with regards to centralization concerns, sops also supports standard pgp/hog keys that you can manage however you wish.

I think the key aspect for a tool as broadly used as dotenv(x) is to be unopinionated about key management (at least on centralized vs decentralized). Because let’s face it, many people are using cloud providers for secret management, and for many people it likely also is a more secure mechanism than keeping keys on local dev machines (especially for larger teams, it takes only one machine to get compromised)

So what sops got right in that regard was that it just supported both centralized (cloud providers) and decentralized (pgp) key management options and gave users the choice :)

**Comment by motdotla** [comment]
> I think the key aspect for a tool as broadly used as dotenv(x) is to be unopinionated about key management (at least on centralized vs decentralized). Because let’s face it, many people are using cloud providers for secret management, and for many people it likely also is a more secure mechanism than keeping keys on local dev machines (especially for larger teams, it takes only one machine to get compromised)

all good thoughts here. that said, I think it's important dotenvx puts some stake in the ground here beyond just what everyone else is doing. that will be `dotenvx pro` - and will be our vision of how this should done. i think it can be done a lot better than tools like AWS KMS. i want us to attempt that.

meanwhile, everything else is just a file generated by dotenvx, which can be managed with unix tools to work with any other tooling like AWS KMS, cloud providers, etc. the `ext` (extensions) will support this effort.

so closing this issue and conversation moving here: https://github.com/dotenvx/dotenvx/issues/259
