### ISSUE TITLE
Fish support

### ISSUE THREAD

**Issue by nbbn** [dotenvx/dotenvx#319]
Dear dotenvx Community,
I would like to suggest a new section in examples for [fish shell](https://fishshell.com/).
I know this is exactly the same with bash, but I didn't check it as I was using fish :smile: 

There are fish scripts and single commands.
I had problem with running (in fish prompt):
```{fish}
/home/linuxbrew/.linuxbrew/bin/dotenvx run -- backup.fish
```
I should run instead:
```{fish}
/home/linuxbrew/.linuxbrew/bin/dotenvx run -- fish backup.fish
```

with commands:
```
/home/linuxbrew/.linuxbrew/bin/dotenvx run -- fish -c 'echo $BORG_OPENSSL_PREFIX'
[dotenvx@1.6.2] injecting env (4) from .env
/usr
js@yabba ~/s/config> /home/linuxbrew/.linuxbrew/bin/dotenvx run -- echo $BORG_OPENSSL_PREFIX
[dotenvx@1.6.2] injecting env (4) from .env
(no output)
```

Silly thing, but I spent some time to understand why it doesn't work.

**Comment by motdotla** [comment]
this actually occurs with bash as well because both shells expand any environment variables in the parent shell first, and then run the remainder of your commands (like dotenvx run and echo here)

```
dotenvx run --quiet -- echo Hello $HELLO
```

so you you need to put the second command inside a subshell (which is what you did):

```
dotenvx run --quiet -- sh -c 'echo Hello $HELLO'
```

i actually use fish myself, but didn't think to add an example on the readme. i just did.

<img width="826" alt="image" src="https://github.com/user-attachments/assets/224fc90f-657e-4cd2-a957-a503a6676700">
