### ISSUE TITLE
Proposals for preventing accidental committing of unencrypted secrets

### ISSUE THREAD

**Issue by sbahman** [dotenvx/dotenvx#325]
## Problem
dotenvx aims to provide a more secure handling of environment variables. To use dotenvx we now need to commit .env files which previously was "forbidden". This could encourage 2 ways that secrets might be accidentally committed (and pushed):

1.  We create an encrypted .env file and commit it. To inspect the secret values we decide to decrypt the file with `dotenvx decrypt ...`. Now we have a tracked file with unencrypted secrets. It would take only a small mistake to commit this.
2. Since we have lifted the ban on committing .env files, the likelihood of committing the wrong .env file (one that might be unencrypted) is increased. (e.g. .env.local might be left unencrypted)

## Proposal 1: Pre commit script to check for unencrypted variables
Create and maintain a pre-commit script (for instance with husky) which would check that any .env file being committed does not contain any unexpected secrets.

I have created this for my project which could be used as a base:
```bash
#!/bin/sh
# Script to check if all environment variables in .env.* files are encrypted

# Get all .env.* files
FILES=$(git diff --cached --name-only | grep '\.env\.')


# Define regex pattern for encrypted values
ENCRYPTED_PATTERN='^.*="encrypted:.*"$'

for FILE in $FILES; do
  echo "Checking $FILE..."

    # Skip files ending with '.example'
  if echo "$FILE" | grep -q '\.example$'; then
    echo "Skipping $FILE (example file)"
    continue
  fi

  # Fail if .keys file is found
  if echo "$FILE" | grep -q '\.keys$'; then
    echo "Error: Found .keys file: $FILE"
    exit 1
  fi


  # Read the file line by line
  while IFS= read -r LINE; do
    # Skip lines that are comments or empty
    if echo "$LINE" | grep -q '^#' || [ -z "$LINE" ]; then
      continue
    fi

    # Check if it's the public key line and skip it
    if echo "$LINE" | grep -q '^DOTENV_PUBLIC_KEY'; then
      continue
    fi

    # Check if the line matches the encrypted pattern
    if ! echo "$LINE" | grep -qE "$ENCRYPTED_PATTERN"; then
      echo "Error: Unencrypted variable found in $FILE: $LINE"
      exit 1
    fi
  done < "$FILE"
done

exit 0
```

## Proposal 2: Different naming convention for unencrypted and encrypted files

dotenvx could rename files when encrypting/decrypting them which would make them drop in and out of being tracked by git. For example, dotenvx could append `.encrypted` to any encrypted files. We can then set .gitignore to ignore all files containing `.env` unless they end with `.encrypted`.

<table style="border-collapse: collapse; border: none;">
  <tr>
    <td>unencrypted</td>
    <td><code>.env.development</code></td>
    <td>untracked</td>
  </tr>
  <tr>
    <td>encrypted</td>
    <td><code>.env.development.encrypted</code></td>
    <td>tracked</td>
  </tr>
</table>

**Comment by motdotla** [comment]
thanks for the thoughts here @sbahman. let's open it to others to contribute their ideas around this.

1. there is an existing precommit hook: `dotenvx ext precommit --install`

a. source: https://github.com/dotenvx/dotenvx/blob/main/src/cli/actions/ext/precommit.js
b. it makes sure the file is full encrypted, otherwise it throws

maybe we should make this first-class rather than under the `dotenvx ext(ensions` ?

2. i have mixed feelings on the `.encrypted` extension and similar like `.crypt`, or `.enc`

I thought about this during the original design and on the one hand it clarifies things. On the other hand, it increases developer cognitive load because now you are encrypt/decrypting across two different files. In addition, the aesthetics of it I don't particularly like.

that said, you can effectively do this now for your own flows like so:

```
dotenvx encrypt --stdout > .env.encrypted
dotenvx decrypt -f .env.encrypted --stdout > .env
```

Something I thought about is different 'modes' for dotenvx. Maybe this could be a mode you opt-in to. But that could get unwieldy too.

Leaving this open and let's get further thoughts from yourself and others.

**Comment by sbahman** [comment]
Cool that there already is a precommit hook. I tried to test it by adding an unencrypted environment variable and then running `dotenvx ext precommit` but that returns `[dotenvx@1.6.4][precommit] success`. When I install it as a git hook then it works as expected though. Am I doing something wrong?


Regarding point 2.

I agree that something like `.enc` would increase developer cognitive load (and bad aesthetics). Ppersonally I think the increased confidence that comes with being able to see the encrypted files from the file extension and being more sure that I won't accidentally push my secrets would more than make up for it. 

Emulating this manually with `dotenvx encrypt --stdout > .env.encrypted` would not really address the problem since that would rely on each developer knowing and remembering to use this syntax. The same problem would occur if one would have to pass a flag to get this behaviour. I prefer the passive safety of all encrypted `.env` files always ending in `.enc` and `.gitignore` ignoring all `.env` files unless they end in `.enc`. What could also work is if I can set a configuration parameter that dotenvx should always behave this way in my repository and this config is saved in git.

**Comment by motdotla** [comment]
> I tried to test it by adding an unencrypted environment variable and then running dotenvx ext precommit but that returns [dotenvx@1.6.4][precommit] success

i'm not able to duplicate this. is it possible you already had your `.env` file gitignored? if so, it will return success.

as to the `.enc` stuff, i'm still mulling on it.

also, precommit is getting extended to traverse all subfolders as well: https://github.com/dotenvx/dotenvx/issues/333

**Comment by motdotla** [comment]
the precommit hook has gotten even smarter and now traverses all your directories - released as `v1.11.0`

**Comment by motdotla** [comment]
related: https://x.com/budivoogt/status/1832347151336100143

**Comment by robertsLando** [comment]
@motdotla I'm using the precommit hook and it works pretty good but I have a problem now, I used the command ` git update-index --assume-unchanged .env` in order to keep the unencrypted env file locally, now the hook keeps blaming me because of that file but it is not going to be commited. Shouldn't the hook just check for the files that are included into the commit?

**Comment by getlarge** [comment]
@robertsLando that's also what i would expect - #376

**Comment by motdotla** [comment]
yeah @getlarge brought this up and he's right. i haven't been able to get to it yet though. @getlarge i know you're busy too but maybe another PR contribution :). if you have time. otherwise will try and get to it.

**Comment by motdotla** [comment]
`1.14.0` and greater has this, thanks to @getlarge 

<img width="538" alt="image" src="https://github.com/user-attachments/assets/59f36009-ad74-43e0-87f3-dfbabfee8020">
