### ISSUE TITLE
Throw an error when there is private/public key missmatch

### ISSUE THREAD

**Issue by RIP21** [dotenvx/dotenvx#327]
Currently, if you mess up your public key, the CLI tool continues to decrypt/encrypt like nothing happened. It should throw an error.

If you break your private key, it does not throw an error either but just stops decrypting.

**Comment by motdotla** [comment]
effort started here: https://github.com/dotenvx/dotenvx/pull/339/files

**Comment by motdotla** [comment]
we won't throw an error since that is not the spirit of dotenv or dotenvx, but we will bumble up warnings. also, there is a scenario where someone provides multiple keys comma separated - for the purpose of key rotation. we don't want to fail on that - one key will fail and one will succeed.

that said, we will also provide a mechanism to fail fast i think. so instead of a warning it will error and process exit code 1

**Comment by RIP21** [comment]
Also, the more options there are (like fail fast or not), the more I feel there should be some configuration file so as not to pass too much stuff into the CLI repeatedly. But that's up to you.

BTW what do you mean key rotation? Like having multiple private keys and multiple public keys and then, probably, using dotenvx programmatically to iterate over them trying to match? Can't see anything about it in the docs.

**Comment by motdotla** [comment]
> multiple private keys and multiple public keys and then, probably, using dotenvx programmatically to iterate over them trying to match

yes. it's not documented yet as it's not flesh out well yet.

> the more I feel there should be some configuration file

i think so too, but i haven't settled on a good dx for this yet. i'm hesitant to add yet another config file.

**Comment by motdotla** [comment]
released in 1.8.0


https://github.com/user-attachments/assets/e867c3b9-f604-4a86-bd24-084eded379cc
