### ISSUE TITLE
Issues while using dotenv-x with dotenv-expand

### ISSUE THREAD

**Issue by robertsLando** [dotenvx/dotenvx#437]
Seems that dotenv-x encrypt/decrpyt uses single quotes instead of double quotes and this breaks dotenv-expand as it skips expand when there is a single quote

cc @getlarge

**Comment by motdotla** [comment]
@robertsLando what version are you on?

I've made some recent fixes/changes around that since `1.21.0` and greater. it *should* now:

1. respect the quotes you give it whether encrypted or decrypted (choose your quotes)
2. single quotes do NOT expand
3. any other quotes or no quotes DO expand
4. (this is different behavior than the original [dotenv-expand](https://github.com/motdotla/dotenvx-expand) which expanded ALL quotes)

however, a couple versions before that it did encrypt things to be wrapped by single quotes.

sorry about all the recent changes. been nailing down a lot of edge cases around expansion and control around expansion.

**Comment by robertsLando** [comment]
I'm using version 1.19.3 right now, will try with latest to see if that fixes the issue. Thanks 🙏🏼

**Comment by motdotla** [comment]
yeah apologies for that! and if your .env file has single quotes in it you'll probably have to manually replace those with double quotes.
