### ISSUE TITLE
[Query] What is the recommeded practice when using docker ?

### ISSUE THREAD

**Issue by gmkumar2005** [dotenvx/dotenvx#451]
What are the best practices for securing .env.keys files? Are they managed similarly to SSH keys? 

Additionally, when running an application inside a Docker container, what is the recommended approach for injecting the 
DOTENV_PRIVATE_KEY securely?
- Is it safe to be used in ConfigMap and k8s secrets ?
- Is it safe to be used in docker-compose.yml ?

**Comment by motdotla** [comment]
We're exploring best practices for teams and important infra with [dotenvx pro](https://github.com/dotenvx/dotenvx/issues/259)

That said, a good rule of thumb is keep your private key separate from your code. The main goal is to make it so an attacker needs two things - both your encrypted .env file AND the private key. So as long as you are keeping those separate until runtime you are good.

Therefore, config map should be ok as well as k8s secrets, but I would avoid docker-compose.yml because it tends to be in your code and next to your encrypted .env file.

An additional thought, some teams go so far as to also NOT include the encrypted .env file in code. This way they separate three things - the code, the encrypted secrets, and the decryption key - and they bring them all together at runtime. We're keeping in mind support for that with [dotenvx pro](https://github.com/dotenvx/dotenvx/issues/259) as well.
