### ISSUE TITLE
perf: Slow to start on fly.io

### ISSUE THREAD

**Issue by ntorrey** [dotenvx/dotenvx#462]
I suppose this is more of a feature request. I noticed that my cold-starts have taken considerably longer with dotenvx than with the previous vault implementation. I have set up everything according to the fly.io documentation. Are there any tweaks I can do to get faster cold-start times?

**Comment by motdotla** [comment]
how slow are you seeing compared to before? are we talking milliseconds here or seconds?

**Comment by motdotla** [comment]
You're doing everything correctly.

Here's a lengthy answer with the technical reason in bold toward the end.

When I conceived of `dotenvx`, priority number 1 was it had to be a drop-in replacement for `dotenv`. Just swap `require('dotenvx').config()` for `require('@dotenvx/dotenvx').config()` and everything still works. Then add in features of dotenvx as you need. So, from right out the gate, `dotenvx` needed to be written in node.

Priority number 2 was making a cli that could work for node devs. They have `npx` and `npm scripts` so it made sense to build this from the same codebase - a joint cli/lib.

Priority number 3 was making the cli work everywhere. I didn't want to maintain two codebases and have to keep them in sync so it made sense to try and convert the node code into a binary. I thought I could use node's native `--experimental-sea-config` tooling for this but man it sucks so bad. Like absolutely unusable and undocumented with no assurance it will ever come out of experimental.

I then discovered `pkg` - now [yao-pkg](https://github.com/yao-pkg/pkg). It's so great. I absolutely love it. It just works! @robertsLando is doing some great work.

I'm going to digress now a bit and then come back to why this performance issue.

I LOVE Node and its community because it really was made to be for everyone. They got so much right in the early days:

1. A language you already knew
2. Your code could also work on the frontend
3. Npm was packaged with it and was superb for extending your code
4. Npm also made it so easy to give back code to the community by publishing small libraries

Essentially, it made distributing code fun and easy - except for one place - publishing binaries. Node completely ignored that major distribution channel and still has - leaving it to languages like Go, Rust, and C.

Imagine a world where publishing a binary is easy as publishing to npm! That would be wonderful. 

`yao-pkg` is somewhat filling this void, and could possibly in a much bigger way some day. I'm rooting for it.

But there is one big downside currently of `yao-pkg` - speed. **It has to package up the entire node runtime with your binary. That initial cold start of node is what appears so slow.**

*(@robertsLando maybe you can chime in here though with added context and knowledge (Robert maintains `yao-pkg`))*

That said, I've deemed it livably slow given other priorities of the project.

For one, it's only on boot. Your server is going to run for days, months, or even years. Yeah, if you deploy multiple times a day then it is more annoying but ultimately livable.

But two, here's my milestones toward improving the speed:

1. Solidify the surface area of features for `dotenvx` (this is getting close. we're mostly seeing bug issues now and dotenvx is at ~1 Million installs per month and growing rapidly)
2. Solidify the surface area of `dotenvx pro` (this is under development and sort of leads back to #1 because `dotenvx` has to provide mechanism for `dotenvx pro` to hook into)
3. Convert core pieces of `dotenvx` node logic to rust, c, or go code. (I haven't settled on which I prefer yet.)
6. Repeat #3 until the `dotenvx` cli is a small fast executable that works everywhere
7. Package up that small fast executable into the npm module via `postinstall` scripts

3, 4, and 5 are A LOT of work. I can't really finance the effort to complete 2. Step 2 will bring in real money to take `dotenvx` to that next level of performance, completeness, and polish.

Until then, sorry about the slow cold starts.

But all that said, maybe Robert will have some thoughts here. I'm sentimental, and I think a world where people build their single executable clis in node is a better place than a world where they build them in go or rust. 

Afterall, `dotenvx` is already a testament that you can be successful choosing node as your cli. (All my friends told me that was a dumb idea.) Maybe node clis can be pushed even further.

**Comment by motdotla** [comment]
i've also considered packaging up with `deno` or `bun` but both have trouble with the encryption curves last I checked.

**Comment by robertsLando** [comment]
@motdotla I think @ntorrey is actually using packaged dotenvx, right? Because AFAIK packaged apps with pkg takes less time to start as the step of compiling js to bytecode is skipped, at least this is what I notice with my packaged apps.

About SEA I have added support for compiling binaries with sea with pkg, you just have to use `--sea` flag. It has many limitations BTW like that it actually accept a single file as input so in case of complex applications you have to pre-compile them using a tool like esbuild or bpkg to create a single file bundle. Another limitation of sea ATM is that it doesn't have a VFS but I plan to add a custom VFS implementation to pkg sea but no clue when I will do it since requires time.

Till now I never did a test to compare the startup time of running `node index.js` or running index packaged with pkg and index packaged with sea but I can easily do this test to see who wins

**Comment by ntorrey** [comment]
Wow, thank you for the thoughtful response! My architecture needs are changing, so in the end I think I will move away from the cold-start model and just keep the server running (I was trying to save a few dollars a month!). Since I am starting to have more users it makes sense anyways and provides a much better experience. Recently fly.io introduced the ability to 'suspend' the server rather than completely 'stop' them so that could also be an option in the future, however that negatively affects other parts of my application. So while I think the issue is valid to reflect on, my fickle needs have already changed so it is no longer an issue for me personally!
Per @robertsLando 's question, I am uncertain whether I am using packaged dotenvx or not. Not sure exactly what that means. I basically have set things up according to the fly.io documentation on the dotenvx page.

**Comment by robertsLando** [comment]
@ntorrey No worries all my questions are for @motdotla :)

**Comment by motdotla** [comment]
> using packaged dotenvx, right

Yes, he's using packaged (via yao-pkg) dotenvx, as those are the instructions in the [Fly guide](https://dotenvx.com/docs/platforms/fly)

<img width="1750" alt="image" src="https://github.com/user-attachments/assets/5d6a7254-6829-4b14-ac1a-9d8b43c23860">

> Because AFAIK packaged apps with pkg takes less time to start 

I've noticed just the opposite. Installing `@dotenvx/dotenvx` to my npm scripts and using in that manner to run `dotenvx run` is faster than using the binary. However, I notice the binary is only slow on that first `dotenvx run` when freshly installed to my machine. After that performance appears equal.

Related experiences: https://github.com/vercel/pkg/issues/859
Here's dotenvx's bundle size: https://bundlephobia.com/package/@dotenvx/dotenvx@1.25.1

> Till now I never did a test to compare the startup time of running node index.js or running index packaged with pkg

This would be great to have some metrics or insight into if possible. If you get a chance to look into any of this let me know here or on twitter dm.

**Comment by robertsLando** [comment]
@motdotla Could be worth a try usign a pre-build step with esbuild to bundle the application before packaging it, let me do some tests on a PR

**Comment by motdotla** [comment]
@ntorrey can you give `1.25.2` or greater a shot?

@robertsLando I did a basic performance test. here's a visual of it. feels a bit more performant.

https://github.com/user-attachments/assets/ce1901f8-4bf3-4555-8bd2-9429f6a85a99

**Comment by robertsLando** [comment]
@motdotla Could you check if you have something inside ~/.pkg folder? Just to see if pkg is actually extracting something there on startup. 

Another thing you could do is to integrate a first command inside the sh script (I know that's kind of cheating but then users will not notice the speed decrease on first run)

**Comment by motdotla** [comment]
i don't see a `~/.pkg` folder on my machine.

> integrate a first command inside the sh script

this isn't sh script related though. the sh script just installs the binary to the user's `/usr/local/bin` directory. that speed decrease is when i first try to execute the binary.

**Comment by ntorrey** [comment]
@motdotla I hope I didn't just send you on a wild goose chase. I think my testing was flawed. It looks like the delay may come from another third-party library that is initializing on server startup. dotenvx does not take nearly as much time as I thought. I was console.logging 'server startup' _after_ initializing some other libraries and that is where the delay is coming from 🤦.   My use of these third party libraries happened to change at the same time that I changed the dotenvx version.
In either case, I don't notice much of a difference between the older and the newer version.

**Comment by robertsLando** [comment]
Oh just noticed that you are using `--no-bytecode` option, that's why you don't see much difference. Is there a specific reason why you are using that? @motdotla

**Comment by motdotla** [comment]
oof. i couldn't tell you @robertsLando. it was so long ago. probably was user error being new to the tool. t

hanks for catching this. i'm switching it off now and so far so good. likely releasing shortly.

**Comment by motdotla** [comment]
feels faster. i'm going to mark this done. thanks everyone for your help!

https://github.com/user-attachments/assets/cf663539-1263-47d1-ba72-a9e1d4b89394

**Comment by ntorrey** [comment]
🎉
