### ISSUE TITLE
error code: `[MISSING_PRIVATE_KEY]`

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#464]
### Are you getting this error?

```sh
[MISSING_PRIVATE_KEY] could not decrypt KEY using private key 'DOTENV_PRIVATE_KEY='
```

### How to fix:

Set `DOTENV_PRIVATE_KEY` on your ci or server where you are receiving this error. It means dotenvx does not have access. It expects the `DOTENV_PRIVATE_KEY` to either be available at `.env.keys` or already in `env`.

### More

Still tripped up? Leave your comment below and I'll help debug for you. Suggestions also welcome!

**Comment by motdotla** [comment]
closing this but if you run into this error and need help just @ me @motdotla. I will re-open and help. This issue is for helping each other debug configuration errors around encryption/decryption.

**Comment by gigamesh** [comment]
@motdotla hey mot, I'm getting this on Railway. I have DOTENV_PRIVATE_KEY_PROD set as a shared env var and am sharing it with my server, but dotenvx isn't picking it up.

**Comment by gigamesh** [comment]
It turns out it was because I didn't have it listed in my turbo.json `globalEnv` field. https://turbo.build/repo/docs/reference/configuration#globalenv

thanks!

**Comment by ontoneio** [comment]
@motdotla I have a repo on WSL2 that was recloned due to an issue with the filesystem and now I lost all my `.env.keys` decryption values. Is there anyway to decrypt the encrypted values?

It's not clear, if I `set` and encrypted variable to recreate the `.env.keys` that value wont necessarily work on the encrypted file will it?

**Comment by ontoneio** [comment]
@motdotla it happens! No worries I think I will be fine. I got it recreated just fine. 

So another question! My organization already pays for 7 users on `dotenv-vault` and since we have switched over to `dotenvx` we haven't been utilizing it as much. Any way to conveniently migrate over from that to Ops since its around the same price? 

Let me know if there's a better channel for this question. 😅

**Comment by motdotla** [comment]
Yeah shoot me an email: mot [at] dotenvx [dot] com
