### ISSUE TITLE
error code: `[WRONG_PRIVATE_KEY]`

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#466]
### Are you getting this error?

```sh
[WRONG_PRIVATE_KEY] could not decrypt KEY using private key 'DOTENV_PRIVATE_KEY=priv...'
```

It means you are using a valid private key but for the wrong environment.

### How to fix:

Check your `DOTENV_PRIVATE_KEY` of `DOTENV_PRIVATE_KEY_${environment}. You likely accidentally mismatched them when setting them.

Also, remember that it is necessary you name your `DOTENV_PRIVATE_KEY` correctly according to environment:

* `.env` -> `DOTENV_PRIVATE_KEY`
* `.env.production` -> `DOTENV_PRIVATE_KEY_PRODUCTION`
* `.env.${environment}` -> `DOTENVX_PRIVATE_KEY_${environment}`
* and so on

### More

Still tripped up? Leave your comment below and I'll help debug for you. Suggestions also welcome!

**Comment by bombamong** [comment]
I got the same error while running `dotenvx run ...`, but managed to solve it by adding the `--overload` flag.
It seems like this error is thrown if there an environment variable has already been set with a diferent `.env.*` file.

### Example
```
dotenvx run -f .env.production --overload -- node index.js
```

**Comment by motdotla** [comment]
working on reproducing. were you loading from multiple .env* files or just that single .env.production file?

**Comment by motdotla** [comment]
I can't reproduce this @bombamong, but I'm glad you got it working. It shouldn't be related to `--overload` as typically this means you are using the wrong environmental private key. (I added some notes in the description above to clarify)

**Comment by skulltech** [comment]
There is indeed an issue here, but strangely it's only occurring with one of my projects and not the others. I can decrypt and view the file using `dotenvx decrypt`, but when I do `dotenvx run` with the same private keys, it throws this `WRONG_PRIVATE_KEY` error. And I did pass multiple dotenv files using the `-f` argument so it might be related to that.

@motdotla

**Comment by motdotla** [comment]
@skulltech can you isolate with `-f` argument is causing that for you by testing each `dotenvx run -f` individually?

**Comment by Th0rgal** [comment]
I can confirm reinstalling node and dotenvx through node fixed it but it would be cool to support bun

**Comment by motdotla** [comment]
> since I update my node to bun

I haven't personally checked but it might be that bun doesn't support the necessary native cryptography APIs yet.

But the workaround for that is to use dotenvx outside of code. Don't use `require('dotenvx').config()`. Instead install the binary and use it as a wrapper: `dotenvx run -- your-bun-start-command`

**Comment by amatiash** [comment]
I recently encountered this error with a Node.js app in production. Here's what I did:

1. Created encrypted `.env.development` and `.env.production` using `dotenvx encrypt -f .env.development` and `dotenvx encrypt -f .env.production`. This generated a `.env.keys` file containing both `DOTENV_PRIVATE_KEY_DEVELOPMENT` and `DOTENV_PRIVATE_KEY_PRODUCTION`.

2. Committed `.env.development` and `.env.production` to git (safe since they're encrypted).

3. Used a conditional to load the correct env file based on `NODE_ENV`:
```typescript
import * as dotenvx from '@dotenvx/dotenvx'

dotenvx.config({
    path: process.env.NODE_ENV === 'PRODUCTION' ? '.env.production' : '.env.development',
})
```

4. We are using PM2 in production. PM2 is configured  to set `NODE_ENV` to `PRODUCTION` (`pm2.config.json`):
```json
{
  "apps": [
    {
      "name": "server2",
      "script": "./build/index.js",
      "node_args": "--import /home/ubuntu/project/build/instrument.js",
      "instances": 2,
      "exec_mode": "cluster",
      "env": {
        "NODE_ENV": "PRODUCTION"
      }
    }
  ]
}
```

5. Removed `DOTENV_PRIVATE_KEY_DEVELOPMENT` from `.env.keys` on the production server (why would we need the dev private key in production?).

**Result:** I received this error:
```
[WRONG_PRIVATE_KEY] could not decrypt [SOME_VARIABLE] using private key 'DOTENV_PRIVATE_KEY_PRODUCTION=xxxxxxx'
```

**Expected behavior:** dotenvx should only attempt to decrypt `.env.production` using `DOTENV_PRIVATE_KEY_PRODUCTION` and should not require `DOTENV_PRIVATE_KEY_DEVELOPMENT` to be present.

P.S. I'm aware of the option to use `dotenvx run`, but I prefer using `@dotenvx/dotenvx` programmatically for ease of setup. Everything works locally in the development environment without the production private key present. I don't understand why I'm seeing this error in production, any ideas?

**Comment by UsmanDev24** [comment]
> I got the same error while running `dotenvx run ...`, but managed to solve it by adding the `--overload` flag. It seems like this error is thrown if there is an environment variable that has already been set with a different `.env.*` file.
> 
> ### Example
> ```
> dotenvx run -f .env.production --overload -- node index.js
> ```
Same case with me when i use `--overload` everything work fine. 
**I investigated it deeply and found the exact cause to this problem here** 
https://github.com/dotenvx/dotenvx/issues/466#issuecomment-4469439700

**Comment by amatiash** [comment]
> > I got the same error while running `dotenvx run ...`, but managed to solve it by adding the `--overload` flag. It seems like this error is thrown if there is an environment variable that has already been set with a different `.env.*` file.
> > ### Example
> > ```
> > dotenvx run -f .env.production --overload -- node index.js
> > ```
> 
> Same case with me when i use --overload everything work fine.

Thanks for sharing the solution!

**Comment by UsmanDev24** [comment]
> > since I update my node to bun
> 
> I haven't personally checked but it might be that bun doesn't support the necessary native cryptography APIs yet.
> 
> But the workaround for that is to use dotenvx outside of code. Don't use `require('dotenvx').config()`. Instead install the binary and use it as a wrapper: `dotenvx run -- your-bun-start-command`
> 
> P.S. For anyone else commenting, next time can you state if you are using a runtime other than node.js.

@motdotla @amatiash @Th0rgal @bombamong 
### The Problem ( Not in Dotenvx )

When running encrypted environments with the following configuration:

```json
"scripts": {
    "start": "dotenvx run -f .env.production -- bun ./dist/app.mjs",
    "dev": "dotenvx run -f .env.development -- bun ./src/app.mjs"
}

```

`bun run dev` works perfectly, but `bun run start` crashes with a `[WRONG_PRIVATE_KEY]` error.

#### Why this happens (Bun vs Dotenvx)

1. **Bun Eager-Loads Early:** When you run `bun run start`, Bun scans your directory *before* executing the script. Because `NODE_ENV` is not explicitly set yet, Bun defaults to a development state and eager-loads your `.env.development` file.
2. **Environment Pollution:** Bun populates your shell with **Development Ciphertext** (.env.development).
3. **Key Mismatch:** `dotenvx run -f .env.production` kicks off, finds the encrypted strings already in the environment, and tries to decrypt them using your `DOTENV_PRIVATE_KEY_PRODUCTION`. Because a production key cannot decrypt .env.development, it panics.

#### Note on different .env variable:
**Error is thrown both in npm and bun  if there is an environment variable that has already been set and  encrypted with a different DOTENV_PRIVATE_KEY.**

#### Note on Node.js / npm:

This issue is **strictly isolated to Bun**. npm is purely a script runner and doesn't load env files automatically, while Node.js requires explicit flags (`--env-file`) to load secrets. Neither will pre-pollute your environment behind your back.

---

### The Solution

The foolproof fix is to **explicitly set `NODE_ENV` at the start of your script**. This forces Bun to eager-load the correct .env file right away, matching your production private key perfectly.

```json
"scripts": {
    "start": "NODE_ENV=production dotenvx run -f .env.production -- bun ./dist/app.mjs",
    "dev": "NODE_ENV=development dotenvx run -f .env.development -- bun ./src/app.mjs"
}

```
