### ISSUE TITLE
.config() is poorly documented

### ISSUE THREAD

**Issue by scottdotweb** [dotenvx/dotenvx#482]
The [npm installation guide](https://dotenvx.com/docs/install#npm) includes the following in the usage example:

```js
require('@dotenvx/dotenvx').config()
```

What `.config()` does isn't explained.

There's no mention of it in either [the quickstart guide](https://dotenvx.com/docs/quickstart) or [the advanced docs](https://dotenvx.com/docs/advanced). The top search result for "config" is the [history of the .env format](https://dotenvx.com/docs/env-file#history) which happens to use the word "config". The second is the [installation guide for Trigger.dev](https://dotenvx.com/docs/background-jobs/triggerdotdev#install-dotenvx), which contains this example:

```js
// Load environment variables
dotenv.config({path: ".env.production"});
```

\- so it appears to be equivalent to `-f` on the command line.

There's no description of all the possible elements of a configuration, or explaining what happens if `.config()` is called without a configuration object. 

This function could do with being explicitly documented.

**Comment by motdotla** [comment]
indeed. good point. 

this is because I cognitively defaulted to [dotenv](https://github.com/motdotla/dotenv) documentation for it. It started mainly as a mechanism to make migration to dotenvx easy. But dotenvx has grown, and it should be documented. I'll get to it soon.

I did recently add it here: https://github.com/dotenvx/dotenvx?tab=readme-ov-file#config-

but needs to be added to [/docs](https://dotenvx.com/docs) as well.

**Comment by scottdotweb** [comment]
Thank you! And for dotenvx in general, it's great.

**Comment by motdotla** [comment]
now available: https://dotenvx.com/docs/advanced

<img width="1626" alt="image" src="https://github.com/user-attachments/assets/b997d136-f9bd-4467-9322-7fd39145161c">


thanks for pointing out that this was missing. 🙏
