### ISSUE TITLE
Do not regenerate `PUBLIC_KEY` if `DOTENV_PUBLIC_KEY` exists

### ISSUE THREAD

**Issue by bingtsingw** [dotenvx/dotenvx#493]
I have a `.env.dev` like this:
```
DOTENV_PUBLIC_KEY="e06d573ea868c89af3e102fcb49b47f5c929ed75d573e0691365e764504e5225c8"
HOST="A"
```

After running `dotenvx encrypt -f .env.dev`
It becomes:
```
#/-------------------[DOTENV_PUBLIC_KEY]--------------------/
#/            public-key encryption for .env files          /
#/       [how it works](https://dotenvx.com/encryption)     /
#/----------------------------------------------------------/
DOTENV_PUBLIC_KEY_DEV="e06d573ea868c89af3e102fcb49b47f5c929ed75d573e0691365e764504e5225c8"

# .env.dev
DOTENV_PUBLIC_KEY="e06d573ea868c89af3e102fcb49b47f5c929ed75d573e0691365e764504e5225c8"

HOST="encrypted:xxxxxxxxxx"
```

It seems unnecessary to regenerate `DOTENV_PUBLIC_KEY_DEV` as they have the same value, and remove `DOTENV_PUBLIC_KEY_DEV` do not affect `decrypt`

**Comment by motdotla** [comment]
this is because your public key was incorrectly named in the `.env.dev` file. It must follow the pattern:

```
.env.ENVIRONMENT => DOTENV_PUBLIC_KEY_${ENVIRONMENT}
```

so if you rename your `DOTENV_PUBLIC_KEY` to `DOTENV_PUBLIC_KEY_DEV` in your original `.env.dev` file you won't have this issue.

**Comment by bingtsingw** [comment]
Not that simple, there are some inconsistencies:

1. when I have `DOTENV_PUBLIC_KEY` **OR** `DOTENV_PUBLIC_KEY_DEV` only, `encrypt`, `get` method works well
2. when I have `DOTENV_PUBLIC_KEY_DEV` only, `run` method throws error, but `DOTENV_PUBLIC_KEY` only works well
3. when I have `DOTENV_PUBLIC_KEY` **AND** `DOTENV_PUBLIC_KEY_DEV`, `run` method need `DOTENV_PUBLIC_KEY` to be behind `DOTENV_PUBLIC_KEY_DEV`

`DOTENV_PUBLIC_KEY_${ENVIRONMENT}` seems to have bugs, and `DOTENV_PUBLIC_KEY` works perfectly for all methods. 

Why I use `DOTENV_PUBLIC_KEY_${ENVIRONMENT}` instead of `DOTENV_PUBLIC_KEY`, this is my scenario:
I want to use **ONE** `DOTENV_PRIVATE_KEY` to manage all my `.env.xxx` file in my repo, so I touch a `.env.xx` file, manually add `DOTENV_PUBLIC_KEY` to it, then add k-v and encrypt it.
This pattern works well, unless the annoying regeneration of seemingly useless  `DOTENV_PUBLIC_KEY_xxxx`

**Comment by motdotla** [comment]
> when I have DOTENV_PUBLIC_KEY_DEV only, run method throws error, but DOTENV_PUBLIC_KEY only works well

What was in your `.env.keys` file at this time? I am betting you were missing the 'DOTENV_PRIVATE_KEY_DEV` key.

**Comment by bingtsingw** [comment]
> What was in your `.env.keys` file at this time? I am betting you were missing the 'DOTENV_PRIVATE_KEY_DEV` key.

Yes, my `.env.keys` file only has `DOTENV_PRIVATE_KEY`, and that's my purpose to use one private key to manage all `.env.xxx` files.

Why I not use `ENVIRONMENT`, in fact I use, but I have many envs in one environment because I use monorepo, so I have `.env.db.dev` `.env.api.dev` `.env.web.dev` etc.
Having lots of `DOTENV_PUBLIC_KEY_XXX_DEV` is annoying, so I manually add several private keys.

**Comment by bingtsingw** [comment]
> this is not so much a power user move but more of a hack

I agree, it's a hack in current design, my operations depend on unexpected library features. It just works in current version.

**Comment by motdotla** [comment]
(Looks like almost all of your `.env*` files are uniquely named so you will only get a moderate advantage to using `-fk` since `-fk` still follows the pattern of `DOTENV_PRIVATE_KEY_${ENVIRONMENT}`.)

Thanks for the thoughts here.

I'll leave this issue open for awhile for others maybe attempting to do something similar.

That said, providing a workaround for the `_ENVIRONMENT` pattern is something I don't anticipate moving away from two reasons:

1. On your server(s) the `run` method uses the `_${ENVIRONMENT}` naming scheme to decide which `.env*` file to load.
2. I want to discourage single private key re-use.

For others (and maybe for yourself) consider maybe consolidating your `.env*` files? Could they be refactored to just 3 at root?

* `.env` (includes all .env and .env.*.dev)
* `.env.ci` (includes ci and test)
* `.env.prod` (all prod related)

Then just preface the keys inside with `API_*`, `DB_*`, etc. I know that is somewhat against what monorepo software tends to recommend, but I've found monorepo software to love complexity and custom configuration a bit too much. Also, I tend to recommend duplicating values across environments - rather than trying to re-use some base `.env` file. Too many edge case mistakes happen trying to treat .env files like code to be refactored super DRY.

**Comment by motdotla** [comment]
closing but if others come across this, please leave your thoughts and @ me.
