### ISSUE TITLE
Load order for .env.*.[extended] files.. - use `-f` flags in order you desire

### ISSUE THREAD

**Issue by jcalfee** [dotenvx/dotenvx#502]
Notice the load order: `.env.staging.local, .env.staging.build, .env.staging, .env.staging.build.local`

```bash
dependencies:
+ @dotenvx/dotenvx 1.32.0

Done in 12.7s
$ >>.env.staging
$ >>.env.staging.local
$ >>.env.staging.build
$ >>.env.staging.build.local
$ DOTENV_PRIVATE_KEY_STAGING= DOTENV_PRIVATE_KEY_STAGING_LOCAL= DOTENV_PRIVATE_KEY_STAGING_BUILD= DOTENV_PRIVATE_KEY_STAGING_BUILD_LOCAL= \
  dotenvx run -- echo
[dotenvx@1.6.4] injecting env (0) from .env.staging.local, .env.staging.build, .env.staging, .env.staging.build.local
```
Instead, should this be: `.env.staging.build.local, .env.staging.local, .env.staging.build, .env.staging`?

Loading all the `.local` files first is consistent with the more common case:

```bash
$ >>.env
$ >>.env.local
$ DOTENV_PRIVATE_KEY= DOTENV_PRIVATE_KEY_LOCAL= DOTENV_PRIVATE_KEY_STAGING= DOTENV_PRIVATE_KEY_STAGING_LOCAL= \
  dotenvx run -- echo
[dotenvx@1.6.4] injecting env (0) from .env.staging.local, .env.local, .env.staging, .env
```

**Comment by motdotla** [comment]
dotenvx respects the order of your private keys when set on the command line that way. Adjust your order and they should load appropriately to how you desire.

**Comment by motdotla** [comment]
closing but let me know if adjusting that does not work. Alternatively, you can use multiple -f flags to denote order.

**Comment by motdotla** [comment]
from your example they are. can you be more descriptive please. where are you setting them?

**Comment by jcalfee** [comment]
The environment variables appear before the command and do not appear in process.argv.  Dotenvx does not have any way to determine order so it must use logic to do that.  

It is smart enough to replace the last '.' in `.env.staging.build` with an underscore (..._STAGING_BUILD) so it appears that this is the supported method, additionally you get into trouble if you try to use '.' in environment variable names (probably why dotenvx does this).  So, it appears that it was coded properly when only one level deep, but that multiple levels are only partially supported so I'm thinking this is an issue.

**Comment by jcalfee** [comment]
Since load order matters, this should be deterministic and load most specific to least specific (e.g. loading `.env.staging` before `.env`).

**Comment by motdotla** [comment]
ok, i dug into this and it is different than I remember:

1. `dotenvx` can NOT determine order via `DOTENV_PRIVATE_KEY*` before the command. This is not a limitation of dotenvx but a limitation of how operating systems handle environment variables (unordered hash table) and how shells parse them as well. They are not guaranteed in either case and so cannot be relied on. (On my particular machine, taking your example, `DOTENV_PRIVATE_KEY_STAGING` ended up toward the end of my `env` but the others ended up almost at the beginning. 🤷
2. because of this limitation you must use `-f` flag. That guarantees order. For example, you can do this:

```
DOTENV_PRIVATE_KEY_STAGING= DOTENV_PRIVATE_KEY_STAGING_LOCAL= DOTENV_PRIVATE_KEY_STAGING_BUILD= DOTENV_PRIVATE_KEY_STAGING_BUILD_LOCAL= dotenvx get -f .env.staging -f .env.staging.local -f .env.staging.build -f .env.staging.build.local
```

---

> Loading all the .local files first is consistent with the more common case:

Where does this concept come from? Is there a web framework you are using that recommends this? Can you let me know which?

**Comment by jcalfee** [comment]
>> Loading all the .local files first is consistent with the more common case:

> Where does this concept come from? Is there a web framework you are using that recommends this? Can you let me know which?

No, I saw it in dotenvx and thought it was intentional!  Lol.  It worked out so well though, I'm attached to this now.  Just load most specific to least specific with .local being the most specific (.local has to be that way, the purpose of local is to overwrite things for the machine and not check it in).

I intentionally did not go the `-f` flag for this use-case because there are layers of programs starting each other (like docker's CMD -> dotenv -> npm -> vite -> vite based kit -> code).  It is just way more difficult in these setups to deal with parameters when the parameters need to change per environment.  For example, trying to get info into node without messing up other environments or complicating the startup can be next to impossible without NODE_OPTIONS to save the day.  Another example are docker deploys like Dokku, Heroku, etc. support environment variables already, so it is always nice to have less configuration to do when it comes to launching the programs in their environment; additionally, launching them depends on where in the launch stack you are and how they are handling command line parameters (npm scripts have quarks when it comes to some types of arguments for example).  I tend to give up if I have to make it that complicated.  Parameters may still be used, but for the main environment, I much prefer trying to keep it simple and only to available environment variables.

The logic for deterministic loading can be reasonably simple.

- most specific to least specific
- ALL .local are the most specific of all
- extended depth determines specificity (.env.staging.build is more specific than .env.staging)
- if specificity is equal, sort

The last one: sort leaves more to be desired.  However, consider that is probably always better to do something here rather than nothing and leave the behavior non-deterministic.  Postgres uses this approach with its triggers.  If trigger order is not clear, they execute in sort order.  So, there should never be a case when you don't know what order something is going to happen (needs to be deterministic).

**Comment by motdotla** [comment]
> The logic for deterministic loading can be reasonably simple.

I disagree given how complicated this is getting with 4 to 5 different files.

```
The logic for deterministic loading can be reasonably simple.

most specific to least specific
ALL .local are the most specific of all
extended depth determines specificity (.env.staging.build is more specific than .env.staging)
if specificity is equal, sort
```

that is the opposite of simple. it requires a lot of knowledge for the beginning user to hold in their head. the beauty of dotenv was always a simple single file and I do my best to continue that legacy.

> it is always nice to have less configuration

Indeed. I'm a big proponent of this which is why I personally recommend against multiple `.env` files for almost a decade. I acknowledge now there is a good use case per environment but I'm still greatly against *.local and other complications.

So I'm not going to implement this. Use `-f` for your needs if you want to continue using such a setup. Otherwise, I recommend consolidating to simple `.env.${environment}`. It is not a bad thing to duplicate values across environments. And user's who need to override a a database url for example locally can then use just one single `.local` and customize their dev load command to additionally add that via `-f .env.local`. I'm highly recommend against using `.local` for any environments except dev `.env`.

Thank you for your thoughts, but I won't be implementing any of this. Others are welcome to add their thoughts on this closed issue in the future and I will consider them. My own tastes can change over time as I experience more, but keep in mind I'm very allergic to complexity and configuration. My goal is to minimize so that dotenvx will always be the simplest alternative to secrets on the market.

**Comment by jcalfee** [comment]
Ok, forget about `.env.staging.build`.  Can we at least get these in order? As follows:

`[dotenvx@1.6.4] injecting env (33) from .env.staging.local, .env.staging, .env.local, .env`

This seams like the only intuitive useful order.  If we can agree on the order, then call it an "edge-case" if you want and keep telling everyone to use `-f` instead.  But, still, wouldn't it be better that this "edge-case" at least be consistent?  People are going to see this working one way then it will change on them (I just saw this change on me).  They, like myself, are not even going to know this is an edge case.  I think the above order is actually quite intelligent, it is really well though out and is working great for me.  But anyways, edge case or not, if it were me I would feel better on everyone's behalf if this were consistent.
