### ISSUE TITLE
Usage in Monorepo

### ISSUE THREAD

**Issue by zach-pp** [dotenvx/dotenvx#52]
I have a monorepo with `.env` files in `packages/env-config`, which are extended into `apps/web`. However upon building, the `packages/env-config` config seems to have not loaded (yet?) so the env validation is failing. Do I need to specify *all* .env files when executing `dotenvx`, or can I set some sort of ordering?

**Comment by motdotla** [comment]
what did you create your monorepo with. i haven't experimented with dotenvx and monorepos so will give it a go and report back with the best solution.

(possibly, we add better support for monorepos as well)

**Comment by motdotla** [comment]
ok, added a guide here that i went through: https://dotenvx.com/docs/monorepos/turborepo

a couple questions for your setup:

1. are you using `globalEnv` in your `turbo.json` ?
2. do you have a single `.env` file at the root of your monorepo, or do each your apps have a `.env` file inside of them?

**Comment by motdotla** [comment]
can you share what your "scripts" look like in your `package.json` file. 

you should be seeing a `dotenvx@version` line like this during your build:

```
$ npm run build
[dotenvx@0.14.1] injecting env (1) from .env
docs:dev: - ready started server on 0.0.0.0:3001, url: http://localhost:3001
web:dev: - ready started server on 0.0.0.0:3002, url: http://localhost:3002
```

**Comment by motdotla** [comment]
ok, you just need to modify your run command to point to the path/location of your `.env` file - since it's not under the root.

```
"scripts": {
    "test": "dotenvx run --env-file=packages/config/.env -- turbo test",
    "build": "dotenvx run --env-file=packages/config/.env -- turbo build",
    "build:web": "dotenvx run --env-file=packages/config/.env -- turbo build --filter=@pudgy/pudgy-auth-web",
    "dev": "dotenvx run --env-file=packages/config/.env --debug -- turbo dev",
    "dev:web": "dotenvx run --env-file=packages/config/.env -- turbo dev --filter=@pudgy/pudgy-auth-web",
    "lint": "dotenvx run --env-file=packages/config/.env -- turbo lint",
    "format": "prettier --write \"**/*.{ts,tsx,md}\""
  },
```

does that pick it up? it should give a warning if it does not.

**Comment by motdotla** [comment]
re-opening this. i agree. we're going to build some tooling that supports this kind of thing. it's particularly useful for `nx` users.

**Comment by motdotla** [comment]
@zach-pp and others, progress on this is coming along. we've added 2 commands `dotenvx ls` and `dotenvx encrypt [directory]`

### `dotenvx ls`

Lists your monorepo's `.env*` files:

<img width="455" alt="image" src="https://github.com/dotenvx/dotenvx/assets/3848/7bf73fa5-8c11-4b7b-91cf-3113adee4663">

Of list under a specific project by passing the optional `[directory]` argument:

<img width="601" alt="image" src="https://github.com/dotenvx/dotenvx/assets/3848/01b60ff7-78bc-4232-a6cc-91acb082d9e4">

### `dotenvx encrypt`

Encrypt a project's `.env*` files rather than the entire monorepo:

<img width="690" alt="image" src="https://github.com/dotenvx/dotenvx/assets/3848/6629f296-75e5-4b10-9d2d-73de2f8ea637">

much better (and composable) tooling!

(we're working on `hub push` supporting management of multiple `.env.keys` from a monorepo. then you can do `hub push apps/backend` to securely share and manage your `.env.keys` across your team)
